EWPP-1126: Drupal 9 compatibility fixes.
openeuropa/drupal-module-template pull request #53
Opened 2021-06-07 15:25 UTC by nagyad

2021-06-22 10:41 UTC, sergepavle requested changes

2021-06-22 10:41 UTC, sergepavle commented on composer.json
> +        "composer/installers": "^1.11",
We can keep `~` for this constraint
```suggestion
        "composer/installers": "~1.11",
```

2021-06-22 10:41 UTC, sergepavle commented on composer.json
> +        "drush/drush": "^10.3",
We can keep `~` for this constraint as was before.
```suggestion
        "drush/drush": "^10.3",
```

2021-06-22 10:41 UTC, sergepavle commented on drupal_module_template.info.yml
> +core_version_requirement: ^8 || ^9
I suppose it should be like that:
```suggestion
core_version_requirement: ^8.9 || ^9.1
```
also looks like we have to remove deprecated for 8.9 already key `core` according to this document: https://www.drupal.org/node/3070687.

2021-06-22 10:47 UTC, sergepavle requested changes
Also, the README file has to be updated regarding the introduced runner package for symlinks. As done in other components.

2021-06-24 07:16 UTC, sergepavle commented on drupal_module_template.info.yml
> +core_version_requirement: ^8 || ^9
Drone is failed because you need to remove the deprecated `core` key.

2021-06-24 11:29 UTC, 22Alexandra submitted a review, later dismissed

2021-06-24 11:31 UTC, sergepavle approved these changes

2021-06-29 10:01 UTC, upchuk requested changes
Missing the quotes around "%paths.base%/tests/features" in the behat.yml file.

2021-06-29 10:42 UTC, upchuk commented
> Missing the quotes around "%paths.base%/tests/features" in the behat.yml file.

Nevermind, I saw wrong

2021-06-29 10:42 UTC, upchuk approved these changes

2021-06-29 11:25 UTC, ademarco approved these changes

2021-06-29 11:25 UTC, merged